### ISSUE TITLE
'Result' name in root namespace causes conflicts.

### ISSUE THREAD

**Issue by nuttycom** [deathbeam/parsihax#1]
Hi, there,

Thanks very much for your work on this library; I'd just sat down myself to port @lihaoyi's excellent FastParse library to Haxe, when I discovered your project and found that I could skip the effort. However, I'm encountering a problem related to the fact that the `Result` type is declared in the root namespace.

@fponticelli's thx.core library *also* declares a `Result` type in the root namespace, and even if neither his `Thx` module nor your `Result` is imported explicitly, the haxe compiler chokes with an error along the lines of `Type name Result is redefined from module Thx`. 

Would you consider moving your utility types into a 'parsihax' package, to help avoid such conflicts? I've also asked that @fponticelli consider deprecating his colonies in the root namespace.

Thanks again,

Kris

**Comment by fponticelli** [comment]
thx does not declare `Result` in the root. The only module declared in the root is `Thx` which is totally optional to use. We could move that as well but I don't think it will help in this case.

**Comment by nuttycom** [comment]
@fponticelli I encounter this error *even though I never import Thx*

**Comment by nuttycom** [comment]
@fponticelli the mere fact that `Result` exists as a typedef in the root namespace is sufficient to cause the haxe compiler to complain.

**Comment by deathbeam** [comment]
I am glad that you like this library @nuttycom :smile: . Sorry for late response, I was not checking this repo at all, because it was pretty feature complete, and also I do not thought that anyone will actually want to use it.

Regarding to issue with root level type declaration, yes, I need to fix that. I was so focused on simplest API as possible that I totally forgot about that it can cause problems. I need to update this project anyway, because Parsimmon got few nice API changes recently, and I want to include some of them here.

**Comment by fponticelli** [comment]
@deathbeam just be aware that your lib is now used in production ... thank you! ;)
